### ISSUE TITLE
Change the default values

### ISSUE THREAD

**Issue by rlagers** [Soitora/SweClockers-Dark#1]
I would like default values to be *default* when installing the theme. I think it is better for new users if the layout does not change too much from the original theme on SweClockers. /Lagers

**Comment by Soitora** [comment]
I can look in to that as soon as I have time

**Comment by Soitora** [comment]
![image](https://user-images.githubusercontent.com/10836780/88400918-5405ac80-cdc9-11ea-965a-68ba8a9d0923.png)
I think a good balance is letting the main menu be default but keep the small tweaks custom such as the scrollbar etc.
