### ISSUE TITLE
Compatibility since the latest update of Sweclockers.

### ISSUE THREAD

**Issue by mrazster** [Soitora/SweClockers-Dark#12]
Since Sweclockers updated their market section to “SweClockers Marknad 2.0”.
The colors are off on some elements of the site. I'll provide a screenshot below.

https://i.ibb.co/R2BHKFb/Screenshot-21141-21-14-07.jpg

**Comment by Soitora** [comment]
Thanks for reporting. I'll see if it's something I can patch quickly or if I need to look at it after work tomorrow.

**Comment by mrazster** [comment]
Damn, that was fast !

Thnx...much appreciated !
