### ISSUE TITLE
Invisible banner ads block content with dark theme enabled.

### ISSUE THREAD

**Issue by PontusMagnusson** [Soitora/SweClockers-Dark#14]
![image](https://user-images.githubusercontent.com/42733555/155965697-bcb574eb-2d8f-4322-9184-4c3a340152ec.png)

I think this issue is in regards to the dark theme, since if dark mode is turned off, the banners no longer block the content on pages.

**System**
* Chrome 98.0.4758.102
* Better Sweclockers 2022.2.24.11.51.24
* uBlock Origin 1.41.4

**Comment by Soitora** [comment]
Hey, thank you for the report. 😊 

I am not home right now but quick testing at work shows that disabling the opacity setting for `.ad` fixes this issue:
![image](https://user-images.githubusercontent.com/10836780/156002422-2762accc-bd02-486a-965a-f10cf4b8528b.png)

Honestly seems pretty weird to me that it would affect the clickability, either way I will send out a hotfix for this and look into a sustainable alternative later.

**Comment by PontusMagnusson** [comment]
Super, thank you!
